Add tests for Agents model
Ceredira/CerediraTess_Test pull request #13
Opened 2022-04-25 18:19 UTC by MariaEnokh

Начало написания тестов для модели Агент

2022-04-25 18:20 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/Просмотр записи агента (в системе есть агент со всеми заполненными столбцами).md
> + Просмотр записи агента (в системе есть агент со всеми заполненными столбцами)
Добавить ###

2022-04-25 18:24 UTC, unixshaman commented
1. Добавить нумерацию для каталога Агенты
2. Заменить во всех скриптах шаги по входу на шаг
	1. [Войти на сайт с пользователем "admin"](../../../../0.%20Шаги/1.%20Войти%20на%20сайт%20с%20пользователем%20username.md)
	[название ссылки для человека](https://сама_ссылка)
	Пути ссылок бывают относительные (1.txt = ./1.txt, asdf/1.txt, ./../asdf ) и жесткие (полный путь)
3. Заменить http://192.168.118.128:7801/ на http://{url}/ , обратить внимание что выключена .*
4. Есть скрипты без текста
5. В каждом скрипте заголовок начать с ### 
6. Сделать отступ 4 пробела
7. Заменить Tabы на пробелы
8. Проверить концевые пробелы

2022-04-26 21:45 UTC, ping335 commented
Текст во всех тесткейсах отображается одной строкой

2022-05-01 13:04 UTC, unixshaman requested changes
Просьба внести указанные изменения, после этого я продолжу проверку дальше.

2022-05-01 13:04 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/8. Создание агента. Заполнение всех полей.md
> +1. В таблице есть новый агент
А если на странице 3 таблицы? Поэтому надо стремиться к однозначным проверкам:
В таблице "Список" отображается строка со значением "по тест-кейсу я не понял какое имя подразумевалось" в столбце "Адрес агента (FQDN)"

2022-05-01 13:04 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/7. Редактирование агента в поле ввода Тип ОС (условие есть агент с тип ОС Windows).md
> +1. Выбрать агент с типом ОС Windows
В таких случаях надо конкретно указывать имя агента, тем более у вас есть шаг по созданию агента, только почему-то не ясно где его имя.

2022-05-06 13:06 UTC, ping335 commented on 1. Компоненты/0. Шаги/3. Создать агент agent с типом ОС os_type.md
> +1. Нажать "Администрирование" -> "Агенты"
Данный шаг лучше написать [как в файле 4](https://github.com/Ceredira/CerediraTess_Test/blob/100cddc0dbb960cb63155b4adbbe11ac11fa157a/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/4.%20%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C%20%D0%B0%D0%B3%D0%B5%D0%BD%D1%82%20agent%2C%20%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9%20lock_user%2C%20%D1%81%20%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%BE%D0%B9%20lock_cause%2C%20%D1%81%20%D1%82%D0%B8%D0%BF%D0%BE%D0%BC%20%D0%9E%D0%A1%20os_type%2C%20%D1%81%D0%BE%20%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8%20scripts%2C%20%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%BA%20%D1%80%D0%BE%D0%BB%D1%8F%D0%BC%20roles%2C%20%D1%81%20%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC%20description.md)

2022-05-07 00:17 UTC, ping335 requested changes

2022-05-07 00:17 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/12. Сортировка в столбце Имя скрипта.md
> +1. Сортирует по имени
Лучше написать так:
1. Cписок отсортировался в алфавитном порядке по полю "Имя скрипта"

2022-05-07 04:01 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. [Создать агент "agent_1" с типом ОС Windows](../../../../0.%20Шаги/3.%20Создать%20агент%20agent%20с%20типом%20ОС%20os_type.md)
Нет, это не так, Тип ОС - это обязательное поле, да, оно имеет значение по умолчанию, но лучше дать возможность тестировщику явно указывать что там нужно.

2022-05-07 04:04 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. Выбрать агент "agent_1"
За место слова Карандаш использовать Редактировать запись

2022-05-07 04:06 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/2. Просмотр записи агента со всеми заполненными столбцами.md
> +1. [Создать агент "agent_2", заблокированный "admin", с причиной "Для теста 2", с типом ОС "Windows", со скриптами "test.bat", добавленный к ролям "admin", с описанием "Агент для теста 2"](../../../.
Там не заполнены все поля, также агент по умолчанию может чуть-чуть поехать, лучше оставить так, как сделано.

2022-05-07 04:07 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/2. Просмотр записи агента со всеми заполненными столбцами.md
> +1. В поле "Роли" присутствует значение "admin"
Вариант без вложенности лучше, так как его проще будет автоматизировать.

2022-05-07 13:39 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. [Создать агент "agent_1" с типом ОС Windows](../../../../0.%20Шаги/3.%20Создать%20агент%20agent%20с%20типом%20ОС%20os_type.md)
Ну может я создала "с типом ОС Linux". Тип более там так по умолчанию стоит

2022-05-07 13:42 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. [Создать агент "agent_1" с типом ОС Windows](../../../../0.%20Шаги/3.%20Создать%20агент%20agent%20с%20типом%20ОС%20os_type.md)
Нам для этого кейса нужен только его "Адрес агента (FQDN)", а остальное линукс там виндовс у него это неважно

2022-05-07 13:49 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. Выбрать агент "agent_1"
Тогда везде менять так...

2022-05-07 13:57 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. [Создать агент "agent_1" с типом ОС Windows](../../../../0.%20Шаги/3.%20Создать%20агент%20agent%20с%20типом%20ОС%20os_type.md)
Концептуально - это важно, нельзя создавать агенты без типа, нет смысла.
Править не надо.

2022-05-07 13:57 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/1. Редактирование агента в поле ввода Адрес агента (FQDN).md
> +1. Выбрать агент "agent_1"
В рамках этого PR, другие тесты задевать не надо.

2022-05-09 14:12 UTC, MariaEnokh commented on 1. Компоненты/0. Шаги/3. Создать агент agent с типом ОС os_type.md
> +1. Нажать "Администрирование" -> "Агенты"
Исправлено

2022-05-09 18:57 UTC, ping335 requested changes

2022-05-09 18:57 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/13. Дублирование скрипта. Сохранить и продолжить редактирование без внесения изменений.md
> +1. Нажать на иконку "Duplicate Row" скрипта с именем "test_1.bat"
"Duplicate Row" заменить на "Дублировать запись" 

и в других кейсах также

2022-05-09 18:57 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/11. Удаление агента, когда запись не последняя.md
>  1. Нажать на иконку "Корзина" агента с адресом "agent_11_1"
"Корзина" заменить на "Удалить запись"

2022-05-09 18:57 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/2. Просмотр записи агента со всеми заполненными столбцами.md
>  1. В таблице "Список" нажать на "Просмотр" в строке со значением "agent_2"
"Просмотр" заменить на "Просмотр записи"

2022-05-09 20:11 UTC, unixshaman requested changes

2022-05-09 20:11 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/17. Сортировка в столбце Описание.md
> +1.%20Войти%20на%20сайт%20с%20пользователем%20username.md)
Мне кажется, или тут Enter и строка разорвана ?

2022-05-09 20:11 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/15. С выбранным. Удалить без выбора.md
> +1.%20Войти%20на%20сайт%20с%20пользователем%20username.md)
Тут тоже Enter

2022-05-09 20:11 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Скрипты/12. Сортировка в столбце Имя скрипта.md
> +1.%20Войти%20на%20сайт%20с%20пользователем%20username.md)
И тут

2022-05-10 14:46 UTC, unixshaman approved these changes

2022-05-10 14:50 UTC, merged