Tests for users
Ceredira/CerediraTess_Test pull request #15
Opened 2022-04-30 01:24 UTC by ping335

2022-05-01 14:39 UTC, unixshaman requested changes

2022-05-01 14:39 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/1. Существование, при старте с нуля, пользователя по умолчанию admin.md
> +1. В главном меню перейти в раздел "Администрирование" -> "Пользователи"
Без кавычек по середине было лучше.

2022-05-01 14:39 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/6. Просмотр записи пользователя.md
> +1. Отобразились все поля и значения пользователя с логином "admin".
Все - это какие? Нужно уточнить каждое поле и что в нем должно быть.

2022-05-01 14:39 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/4. Изменение записи пользователя, изменение поля Логин пользователя.md
> +1. В столбце "Логин пользователя" появился новый логин пользователя "user2"
Лучше это сделать более однообразно с другими кейсами -
В таблице "Список" присутствует строка со значением "user2" в столбце "Логин пользователя"

2022-05-01 14:39 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
Так делать нельзя. В будущем такое поле исчезнет. С пользователем user после такого редактирования войти в систему больше нельзя будет.

2022-05-01 14:39 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Нажать на кнопку "Сохранить"
Я бы продолжил такой тест-кейс с входом пользователя с измененным паролем

2022-05-01 15:21 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/6. Просмотр записи пользователя.md
> +1. Отобразились все поля и значения пользователя с логином "admin".
Тогда и в других тест-кейсах нужно менять? У меня везде так написано было

2022-05-01 15:23 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
Ну его же можно изменить...

2022-05-01 15:25 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Нажать на кнопку "Сохранить"
Ну так если пароль поменять, понятно что по старому паролю уже не войти

2022-05-01 15:27 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
Какое поле исчезнет?

2022-05-01 15:27 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
Там должен быть пароль не в чистом виде, а специальное хэш-значение от пароля. И составить его правильно нельзя. Собственно вставив туда 123 вы получите в приложении Exception .

2022-05-01 15:28 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/6. Просмотр записи пользователя.md
> +1. Отобразились все поля и значения пользователя с логином "admin".
В других кейса этого PR, остальные кейсы думаю лучше отдельным PR_ом изменить, так проще проверять.

2022-05-01 15:29 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
Поле ввода пароля, администратор не должен иметь возможность менять пароль пользователей - это дыра в безопасности, и ее надо закрыть.

2022-05-01 16:14 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
То есть пароль можно поменять только войдя под пользователем user?

2022-05-01 16:19 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Изменение записи пользователя, изменение поля Password.md
> +1. Ввести в поле "Password" значение "123"
А что нужно конвертировать в хэш? Или как тогда поменять пароль? Или этого кейса вообще не должно быть?

2022-05-01 19:17 UTC, unixshaman requested changes

2022-05-01 19:17 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
> +	1. Логин пользователя: admin
Табом нельзя, нужно 2 пробела сюда. Опасайтесь табов всегда.

2022-05-01 19:17 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/4. Изменение записи пользователя, изменение поля Логин пользователя.md
> +1. Нажать на иконку "Редактировать запись" пользователя с логином "user"
Вот это кстати не плохо вышло, наверное, стоит потом так везде сделать

2022-05-02 19:03 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
> +	1. Логин пользователя: admin
Если 2мя пробелами то список продолжается а не вкладывается

2022-05-02 20:44 UTC, unixshaman requested changes

2022-05-02 20:44 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
> +
Тут надо Enter убрать, а то это становится разными списками, путь будет как вложенный список

2022-05-02 20:44 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
> +    1. Дата создания:         "yyyy-mm-dd" "hh:tt:ss"
В оригинале кавычек нет, и еще есть микросекунды

2022-05-02 20:44 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/4. Изменение записи пользователя, изменение поля Логин пользователя.md
> +
Слишком много лишних Enter

2022-05-02 20:45 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Пользователи/5. Просмотр записи пользователя.md
> +	1. Логин пользователя: admin
Окей, 4 пробела годится.

2022-05-03 20:15 UTC, unixshaman approved these changes

2022-05-03 20:17 UTC, merged