Add requirements
Ceredira/CerediraTess_Test pull request #27
Opened 2022-05-11 22:17 UTC by unixshaman

Добавил схему в формате plant uml и сгенерированную из нее svg. При правках файла puml просьба не забывать выполнять регенерацию svg.

2022-05-12 00:46 UTC, ping335 approved these changes

2022-05-12 22:23 UTC, ping335 requested changes

2022-05-12 22:23 UTC, ping335 commented on Требования/CerediraTess.puml
> +****** Вручную бинарный файл
Тут наверно лучше как-то понятнее написать. Или запятую поставить хотя бы.

2022-05-12 22:23 UTC, ping335 commented on Требования/CerediraTess.puml
> +***** Файловый-сервер
тут тире не нужно

2022-05-14 19:23 UTC, unixshaman commented on Требования/CerediraTess.puml
> +****** Вручную бинарный файл
Исправлено, сделал
Вручную, через бинарный файл

2022-05-14 19:23 UTC, unixshaman commented on Требования/CerediraTess.puml
> +***** Файловый-сервер
Исправлено, убрал тире

2022-05-14 19:34 UTC, ping335 approved these changes

2022-05-14 19:37 UTC, merged