Type os
Ceredira/CerediraTess_Test pull request #30
Opened 2022-05-16 07:03 UTC by MariaEnokh

2022-05-16 13:41 UTC, unixshaman requested changes

2022-05-16 13:41 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Типы ОС/3. Создание нового типа ОС.md
> +1. В поле "Agents" из выпадающего меню выбрать "CerediraTess"
Убрать эту строку, в проекте CerediraTess завести дефект: При добавлении нового типа ОС доступно для заполнения поле Agents

2022-05-16 13:41 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Типы ОС/4. Просмотр записи типа ОС.md
> +1. В поле "Имя ОС" присутствует значение "Windows"
Сюда добавить строку
В поле "Агенты" присутствует значение "CerediraTess"

В проекте CerediraTess добавить дефект: При просмотреть типа агента отсутствует список агентов с этим типом.

2022-05-17 02:29 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Типы ОС/3. Создание нового типа ОС.md
> +1. В поле "Agents" из выпадающего меню выбрать "CerediraTess"
А это поле не нужно?

2022-05-18 07:34 UTC, MariaEnokh commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Типы ОС/4. Просмотр записи типа ОС.md
> +1. В поле "Имя ОС" присутствует значение "Windows"
При просмотре типа агента или типа ОС?

2022-05-20 16:50 UTC, unixshaman approved these changes

2022-05-20 17:29 UTC, merged