add positive tests
Ceredira/CerediraTess_Test pull request #31
Opened 2022-05-17 21:00 UTC by ping335

Добавила первые кейсы на блокировку агентов.

2022-05-17 21:12 UTC, ping335 commented
Знаю что 2 ссылки не работают пока не могу понять почему...

2022-05-20 07:38 UTC, unixshaman requested changes

2022-05-20 07:38 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
Это нельзя отсюда вызывать, нужно вынести аналогичные шаги без проверок в Шаги

2022-05-20 07:38 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
Также, не ясно с какой вы причиной заблокировали агент, это обязательно поле, и оно нужно для разблокировки, поэтому тут по кейсу дальше будут проблемы, поле Причина блокировки никак не заполняется.

2022-05-20 07:38 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/4.  Разблокировка n агентов.md
> +1. [Заблокировать агенты "CerediraTess" и "test"](/3.%20Блокировка%20n%20агентов.md)
Этот шаг лучше разбить на 2, типо заблокировать сначала 1 агент, потом второй агент, используя как раз Блокировку агентов с причиной из Шагов

2022-05-20 07:38 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/4.  Разблокировка n агентов.md
> +1. В списке "История блокировок" появилась 1 новая запись - "Результат разблокировки агентов (yyyy:mm:dd hh:mm:ss): Для тестирования"
Причина блокировки не указываалась в тест-кейсе. Также стоит в причину блокировки добавлять номер тест-кейса.

2022-05-21 04:13 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
причина указана в кейсе с разблокировкой на который я ссылаюсь

2022-05-21 11:13 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
>Это нельзя отсюда вызывать, нужно вынести аналогичные шаги без проверок в Шаги

А могу я ссылаться [на скрипт 6 из шагов](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/6.%20%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C%20%D0%B0%D0%B3%D0%B5%D0%BD%D1%82%20agent%2C%20%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9%20lock_user%2C%20%D1%81%20%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%BE%D0%B9%20lock_cause%2C%20%D1%81%20%D1%82%D0%B8%D0%BF%D0%BE%D0%BC%20%D0%9E%D0%A1%20os_type%2C%20%D1%81%D0%BE%20%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8%20scripts%2C%20%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%BA%20%D1%80%D0%BE%D0%BB%D1%8F%D0%BC%20roles%2C%20%D1%81%20%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC%20description.md)? Это создание агента**и блокировка в одном**.
Т.е. он мне отчасти подходит. Чтобы не плодить лишние кейсы. Или надо создать отдельный кейс **где будет только блокировка**?

2022-05-21 11:26 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
>Это нельзя отсюда вызывать, нужно вынести аналогичные шаги без проверок в Шаги

А могу я для этого использовать[ уже созданный 6 кейс](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/6.%20%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C%20%D0%B0%D0%B3%D0%B5%D0%BD%D1%82%20agent%2C%20%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9%20lock_user%2C%20%D1%81%20%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%BE%D0%B9%20lock_cause%2C%20%D1%81%20%D1%82%D0%B8%D0%BF%D0%BE%D0%BC%20%D0%9E%D0%A1%20os_type%2C%20%D1%81%D0%BE%20%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8%20scripts%2C%20%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%BA%20%D1%80%D0%BE%D0%BB%D1%8F%D0%BC%20roles%2C%20%D1%81%20%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC%20description.md)? Там создание агента и **блокировка** в одном.
Просто если я создам отдельный кейс 7 то там получится тоже самое. Потому что мне чтобы заблокировать агент нужно его сначала создать. Я могу взять дефолтный агент CerediraTess но, как я поняла, для кейса из директории Шаги он не подойдет, потому что там нельзя хардкордно написать название (только с маской)

2022-05-21 12:58 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
Лучше так не делать, потому что 6 шаг очень сложный шаг, при вызове сложных шагов пропадает прозрачность. Также, если у тестировщика уже есть агент, он может его просто заблокировать, пропустив создание. Поэтому хорошо будет все же делать 2 шага - простое создание, простую блокировку. С этим проще будет потом жить.
Также, лучше чтобы поле Причина проходила сквозь тест-кейс явно, а не чтобы это было закатано во внутренние шаги.

2022-05-21 13:02 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](1.%20Блокировка%201%20агента.md)
> Также, если у тестировщика уже есть агент, он может его просто заблокировать,

То есть мне так написать выбрать агент CerediraTess в шагах, без маски?

2022-05-21 14:33 UTC, unixshaman requested changes

2022-05-21 14:33 UTC, unixshaman commented on 1. Компоненты/0. Шаги/8. Блокировка агента agent.md
> +1. В поле "Причина блокировки" ввести значение "${lock_cause}"
Параметр lock_cause отсутствует в шапке и в имени файла

2022-05-21 14:33 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess"](../../../0.%20Шаги/8.%20Блокировка%20агента%20agent.md)
Тут не хватает как раз причины блокировки For_testing_1

2022-05-21 14:33 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/4.  Разблокировка n агентов.md
> +1. [Заблокировать агент "test_4"](../../../0.%20Шаги/8.%20Блокировка%20агента%20agent.md)
В эти два шага не забыть добавить причину

2022-05-21 17:13 UTC, unixshaman requested changes

2022-05-21 17:13 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/3.  Блокировка n агентов.md
> +1. [Создать агент "test_3"](../../../0.%20Шаги/10.%20Создать%20агент%20agent%20с%20типом%20ОС%20os_type%20и%20с%20ролью%20role.md)
В описании шага не хватает параметров

2022-05-21 17:27 UTC, unixshaman requested changes

2022-05-21 17:27 UTC, unixshaman commented on 1. Компоненты/0. Шаги/9. Разблокировка агента agent с причиной lock_cause.md
> +### Блокировка агента "${agent}" с причиной "${lock_cause}"
Шапка не соответствует имени файла.

2022-05-21 17:27 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/2.  Разблокировка 1 агента.md
> +1. [Заблокировать агент "CerediraTess" с причиной "For_testing_2"](../../../0.%20Шаги/8.%20Блокировка%20агента%20agent%20с%20причиной%20lock_cause.md)
Имя файла Блокировка... а в описании Заблокировать агент...
Мне нравится вариант Заблокировать агент... , поэтому предлагаю имена файлов и шапки внутри файлов переделать на Заблокировать агент

2022-05-21 17:27 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/2. Основной функционал/Блокировка агентов/4.  Разблокировка n агентов.md
> +1. [Заблокировать агент "test_4" с причиной "For_testing_4"](../../../0.%20Шаги/8.%20Блокировка%20агента%20agent%20с%20причиной%20lock_cause.md)
Тут аналогично комментарию выше.

2022-05-21 17:47 UTC, unixshaman requested changes

2022-05-21 17:47 UTC, unixshaman commented on 1. Компоненты/0. Шаги/8. Заблокировать агент agent с причиной lock_cause.md
> +### Блокировка агента "${agent}" с причиной "${lock_cause}"
Тут осталось Блокировка

2022-05-21 17:49 UTC, unixshaman approved these changes

2022-05-21 17:50 UTC, merged