add tests
Ceredira/CerediraTess_Test pull request #34
Opened 2022-05-21 15:25 UTC by MariaEnokh

2022-05-21 15:29 UTC, MariaEnokh commented
ссылки на 7 файл  в шагах не работают (

2022-05-21 17:44 UTC, unixshaman requested changes

2022-05-21 17:44 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/1. Обновление скриптов.md
> +1. [Добавить скрипт с именем "test1.bat" для агента "CerediraTess"](../../../../0.%20Шаги/7.%20Добавление%20скриптов%20scripts%20для%20существующего%20агента%20agent.md)
Я бы до этого шага добавил проверку, что этого скрипта нет в списке, в этом шаге мы типо добавляем его, потом нажимаем на кнопку Обновить скрипты и проверяем что Скрипт появился. Т.е. последние 2 шага переставить после этого шага.

2022-05-21 17:44 UTC, unixshaman commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. [Создать скрипт "${scripts}"](../../../../0.%20Шаги/2.%20Создать%20скрипт%20с%20именем%20test_name.md)
../../../../0.%20Шаги/ - надо убрать, вызываемый скрипт находится в этом же каталоге

2022-05-21 18:11 UTC, MariaEnokh commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/1. Обновление скриптов.md
> +1. [Добавить скрипт с именем "test1.bat" для агента "CerediraTess"](../../../../0.%20Шаги/7.%20Добавление%20скриптов%20scripts%20для%20существующего%20агента%20agent.md)
Где надо сделать проверку что скрипта нет в списке? 
1)Там где Администрирование-Скрипты
2)Выполнение запросов-поле Скрипты
3) Администрирование-Агенты у агента CerediraTess

2022-05-21 18:20 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/1. Обновление скриптов.md
> +1. [Добавить скрипт с именем "test1.bat" для агента "CerediraTess"](../../../../0.%20Шаги/7.%20Добавление%20скриптов%20scripts%20для%20существующего%20агента%20agent.md)
2)Выполнение запросов-поле Скрипты

2022-05-22 09:47 UTC, ping335 approved these changes

2022-05-22 09:47 UTC, ping335 commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. В таблице "Список" у агента "${agent}" нажать иконку "Редактировать"
заменить на:
нажать на иконку "Редактировать запись"

2022-05-22 09:47 UTC, ping335 commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. Нажать на кнопку "Сохранить"
Нужно написать в конце ожидаемый результат:

1. В таблице "Список" отображается строка со значением "${test_name}" в столбце "Скрипты"

2022-05-22 09:47 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/12. Проверка существования, при старте с нуля, агента CerediraTess.md
> +1. В таблице "Список" в поле "Адрес агента (FQDN)" есть значение "CerediraTess", в поле "Роли" есть значение "admin"
"есть" заменить на "присутствует"

 И в остальных кейсах также поменять

2022-05-22 09:50 UTC, ping335 requested changes

2022-05-22 09:50 UTC, ping335 commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. В таблице "Список" у агента "${agent}" нажать иконку "Редактировать"
заменить на:
нажать на иконку "Редактировать запись"

2022-05-22 09:50 UTC, ping335 commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. Нажать на кнопку "Сохранить"
Нужно написать в конце ожидаемый результат:

1. В таблице "Список" отображается строка со значением "${test_name}" в столбце "Скрипты"

2022-05-22 09:50 UTC, ping335 commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Администрирование/Агенты/12. Проверка существования, при старте с нуля, агента CerediraTess.md
> +1. В таблице "Список" в поле "Адрес агента (FQDN)" есть значение "CerediraTess", в поле "Роли" есть значение "admin"
"есть" заменить на "присутствует"

И в остальных кейсах также поменять.

2022-05-22 11:33 UTC, MariaEnokh commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. Нажать на кнопку "Сохранить"
Это же просто шаги для другого кейса, тут это разве нужно?

2022-05-22 12:35 UTC, unixshaman requested changes

2022-05-22 12:35 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/1. Обновление скриптов.md
> +1. [Добавить скрипт с именем "test1.bat" для агента "CerediraTess"](../../../../0.%20Шаги/7.%20Добавление%20скриптов%20scripts%20для%20существующего%20агента%20agent.md)
В ссылке 1 переход на каталог вверх лишний.

2022-05-22 12:35 UTC, unixshaman commented on 1. Компоненты/1. Веб-интерфейс/3. Вспомогательный функционал/Выполнение запросов/2. Добавление скрипта, когда файл скрипта удален.md
> +1. [Добавить скрипт с именем "test_2.bat" для агента "CerediraTess"](../../../../0.%20Шаги/7.%20Добавление%20скриптов%20scripts%20для%20существующего%20агента%20agent.md)
Тут и выше аналогично прошлому замечанию.

2022-05-22 12:37 UTC, ping335 requested changes

2022-05-22 12:37 UTC, ping335 commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. В таблице "Список" у агента "${agent}" нажать на иконку "Редактировать"
так вы же не поменяли...

2022-05-22 13:01 UTC, unixshaman approved these changes

2022-05-22 13:03 UTC, MariaEnokh commented on 1. Компоненты/0. Шаги/7.  Добавление скриптов scripts для существующего агента agent.md
> +1. В таблице "Список" у агента "${agent}" нажать на иконку "Редактировать"
Прошу прощения не сохранила и пушнула

2022-05-22 13:06 UTC, ping335 approved these changes

2022-05-22 13:25 UTC, merged